### ISSUE TITLE
docker安装之后上传图片失败了

### ISSUE THREAD

**Issue by wick233** [csznet/tgState#1]
docker run -d -p 8088:8088 --name tgstate -e TOKEN=1241176317:xxxxxx -e CHANNEL=@https://t.me/xxxxx csznet/tgstate:latest这个配置哪里有问题嘛

**Comment by csznet** [comment]
只需要@xxxx就行了，比如https://t.me/tgssds 就只需要输入CHANNEL=@tgssds
