### ISSUE TITLE
后端启动报错

### ISSUE THREAD

**Issue by sd362318** [csznet/tgState#11]
root@C20230721219872:~# ./tgState -token ****** -channel @****** -port ****** -mode pan
启动Web服务器，监听端口 ******
2023/10/23 14:09:56 Authorized on account ******
2023/10/23 14:09:56 Endpoint: getUpdates, params: map[allowed_updates:null timeout:60]
2023/10/23 14:09:57 Endpoint: getUpdates, response: ***********************
2023/10/23 14:09:57 Endpoint: getUpdates, params: map[allowed_updates:null offset:747271532 timeout:60]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe8 pc=0x70375f]

goroutine 18 [running]:
csz.net/tgstate/utils.BotDo()
	/home/runner/work/tgState/tgState/utils/utils.go:90 +0x27f
created by main.main
	/home/runner/work/tgState/tgState/main.go:24 +0x85
________________________________________________
请问这是出现了什么问题呢？

**Comment by sd362318** [comment]
后端版本是1.2.6

**Comment by csznet** [comment]
可以正常上传下载文件吗

**Comment by sd362318** [comment]
> 可以正常上传下载文件吗

不可以

**Comment by csznet** [comment]
报错是无法与telegram进行通讯 排查一下channel和bot是否可用

**Comment by sd362318** [comment]
> 报错是无法与telegram进行通讯 排查一下channel和bot是否可用

当我尝试把其他地方的文件转发给机器人然后 get ，后端就报错
