### ISSUE TITLE
下载回来的数据中尾部一些数据丢失

### ISSUE THREAD

**Issue by LanYunDev** [csznet/tgState#21]
超过10MB文件,上传成功后,传输回来得到的文件不是完整的,尾部的一些数据丢失.
服务器docker部署的.链路: vps <-> CDN <-> CF <-> 浏览器

**Comment by csznet** [comment]
tg中有文件集合的txt吗，里面是否有两个fileid

**Comment by LanYunDev** [comment]
下面是示例:
存在两个fileid
<img width="583" alt="image" src="https://github.com/csznet/tgState/assets/95263282/565eee4e-c528-4ba9-8726-ce03879119bb">
<img width="258" alt="image" src="https://github.com/csznet/tgState/assets/95263282/2adb9c08-d9ab-4472-8fb0-f3e5a60b8631">
实际下载:
<img width="293" alt="image" src="https://github.com/csznet/tgState/assets/95263282/9231a374-e470-4bf1-b251-26ff4fdf7c6e">
原图:
<img width="297" alt="image" src="https://github.com/csznet/tgState/assets/95263282/75fb97c0-a7e2-45ff-8e6b-42e685b28264">

**Comment by LanYunDev** [comment]
实测:在私聊和群聊中均会存在此问题

**Comment by LanYunDev** [comment]
我fork拉一份,已修复: https://github.com/LanYunDev/tgState
由于个性化修改地方较多,故不PR了.

**Comment by zhjnerv** [comment]
> 我fork拉一份,已修复: https://github.com/LanYunDev/tgState 由于个性化修改地方较多,故不PR了.

修改了哪里啊，我这里也碰到了一样的问题，希望可以指出一下怎么处理。
