### ISSUE TITLE
上传91M的exe文件失败了

### ISSUE THREAD

**Issue by 2424004764** [csznet/tgState#8]
![image](https://github.com/csznet/tgState/assets/24261680/ef3c19b2-d38c-4a43-aec3-c92863f9f9fe)

**Comment by csznet** [comment]
用的vercel搭建的吗

**Comment by 2424004764** [comment]
@csznet demo里的网址：https://tgstate.vercel.app/   上传小图片是可以的

**Comment by csznet** [comment]
vercel传输有限制，稍微大一点就传输失败，建议使用二进制或者docker自己搭建

**Comment by 2424004764** [comment]
@csznet ok

**Comment by 2424004764** [comment]
可以无限制上传文件？

**Comment by csznet** [comment]
试过8g的上传tg提示过大，后面有时间可能会弄成切片上传的方式，这样就不限制大小了

**Comment by 2424004764** [comment]
国内访问慢的问题有解决方案吗？

**Comment by csznet** [comment]
套cf 优选 或者其他cdn 也可以自己反代

**Comment by 2424004764** [comment]
我目前就是第一种方案

**Comment by k-fire** [comment]
本地搭建上传大于50m的文件也会失败
