### ISSUE TITLE
请问如何安装旧版本？

### ISSUE THREAD

**Issue by chancat87** [csznet/tgState#9]
请问一下如何在非Vercel下，搭建旧版本？
我喜欢旧版本的上传完文件以后在该页面即可点击复制markdown代码。
另外在获取FileID[https://github.com/csznet/tgState#%E8%8E%B7%E5%8F%96fileid](url)，我用的docker方式安装的网盘模式，那要怎样获取+/d/+FileID的地址？因为我使用的频道，当我回复刚上传的图片get并没有任何反应。。

**Comment by csznet** [comment]
推送了网盘模式下支持复制图片的代码，频道获取FileID还没有支持上，目前的是群组or私聊

**Comment by chancat87** [comment]
> 推送了网盘模式下支持复制图片的代码，频道获取FileID还没有支持上，目前的是群组or私聊

好的，多谢回复。
